[[language]]
name = "latex"
scope = "source.tex"
injection-regex = "tex"
file-types = ["tex"]
indent = { tab-width = 4, unit = "    " }
language-server = { command = "ltex-ls" }
[language.config.ltex]
dictionary = { en-US = [
	"rowspace",
	"AES",
	"Abitur",
	"Achronality",
	"Adrea",
	"Aretakis",
	"Boneh",
	"Carmer",
	"Christoph",
	"Civita",
	"ColGame",
	"Crypto",
	"Cryptographic",
	"Cyber",
	"DES",
	"Damg",
	"Damgard",
	"Damgrad",
	"Darboux",
	"Darboux's",
	"Deutsche",
	"Digitalization",
	"ECB",
	"ETH",
	"ETHZ",
	"Elia",
	"FP",
	"FindSecondPreimage",
	"Frederik",
	"Frobenius",
	"Funktionentheorie",
	"GF",
	"Genzel",
	"Ghaffari",
	"Ghez",
	"Govaerts",
	"Hackathon",
	"Healthyways",
	"Hirt",
	"Holomorphic",
	"Hom",
	"KGen",
	"Kaufmann",
	"Kerchoff",
	"Keysize",
	"Linicrypt",
	"Lipschitz",
	"MACs",
	"MDA",
	"Matyas",
	"Maurer",
	"McQuoid",
	"Merkle",
	"Minkowski",
	"Miyaguchi",
	"Mor",
	"Moser",
	"Moser's",
	"Möbius",
	"NEC",
	"NGO",
	"OIE",
	"Oseas",
	"PGV",
	"PRF",
	"PRP",
	"Penrose",
	"Preneel",
	"Rahm",
	"Raychaudhuri",
	"Reinhard",
	"Reto",
	"Ric",
	"Ricci",
	"Riemannian",
	"Rimannian",
	"Rogaway",
	"Rosulek",
	"SHA",
	"Schule",
	"Schwarzschild",
	"Semesterarbeit",
	"Semmel",
	"Shoup",
	"Shrimpton",
	"Stams",
	"Struwe",
	"Swope",
	"Symm",
	"TODOS",
	"ToDo's",
	"Ueli",
	"Universitätsstrasse",
	"Vandewalle",
	"VersusVirus",
	"Vfy",
	"Vigenere",
	"Wehntalerstrasse",
	"Weingarten",
	"Weinstein",
	"Wilwacher",
	"ZAV",
	"Zürich",
	"achronal",
	"achronality",
	"affinely",
	"api",
	"basepoint",
	"bijection",
	"bijective",
	"bilinear",
	"bla",
	"blabla",
	"blocksize",
	"bm",
	"boundedness",
	"ciphertext",
	"ciphertexts",
	"codimension",
	"cohomology",
	"coisotropic",
	"computable",
	"congruences",
	"conv",
	"covariate",
	"cryptographic",
	"darbouxweinstein",
	"de",
	"defn",
	"diffeomorphic",
	"diffeomorphism",
	"dm",
	"ds",
	"dt",
	"dx",
	"dy",
	"e",
	"encryptions",
	"eq",
	"equivariant",
	"extremal",
	"fm",
	"foliate",
	"foliated",
	"foliation",
	"frac",
	"geod",
	"geodesically",
	"geq",
	"goedesics",
	"holomorphic",
	"homeo",
	"homeomorphic",
	"homeomorphism",
	"homotopic",
	"homotopy",
	"hyperbolicity",
	"hypersurface",
	"hypersurfaces",
	"iPhO",
	"ic",
	"iff",
	"ij",
	"im",
	"inextendible",
	"injective",
	"injectively",
	"inputless",
	"instantiation",
	"integrable",
	"invariance",
	"invertibility",
	"invertible",
	"isotopies",
	"isotopy",
	"iteratively",
	"jk",
	"keylength",
	"keysize",
	"len",
	"leq",
	"mathcal",
	"monotonely",
	"moser",
	"newcommand",
	"nonces",
	"numberlike",
	"numberwithin",
	"ok",
	"oplus",
	"orientability",
	"orientable",
	"orthogonally",
	"orthonormal",
	"overtswisted",
	"overtwisted",
	"pM",
	"pS",
	"parallelizable",
	"parallely",
	"parametrized",
	"pathologies",
	"piecewise",
	"plaintext",
	"pointwise",
	"pre",
	"pregeodesic",
	"pregeodesics",
	"preimage",
	"preimages",
	"pseudorandom",
	"reparametrisation",
	"rescaled",
	"samepage",
	"spacelike",
	"spacetimes",
	"submanifold",
	"submanifolds",
	"subsequence",
	"subseteq",
	"subspaces",
	"summands",
	"symplectic",
	"symplectomorphism",
	"th",
	"timelike",
	"todo",
	"toric",
	"traceless",
	"unforgeability",
	"urich",
	"valign",
	"varepsilon",
	"variational",
	"vri",
	"webapps",
	"wl",
	"wlog",
	"xH",
  ]}

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md"
file-types = ["md"]
indent = { tab-width = 4, unit = "    " }
language-server = { command = "ltex-ls" }
